version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gamedealdb_container
    environment:
      POSTGRES_USER: gamedeal
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gamedealdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: gamedeal_app
    command: sh -c "python -m src.db.init_db && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://gamedeal:admin123@db:5432/gamedealdb
    depends_on:
      - db

volumes:
  postgres_data: